version: 0.2

runtime-versions:
  nodejs: 20.x

phases:
  install:
    - npm install

  build:
    - npm run build

  post_build:
    - npm run export

artifacts:
  files:
    - ".next/**/*"
    - "out/**/*"
  discard-paths: yes
